analytics:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_DATABASE','default') }}"
      host: "{{ env_var('CLICKHOUSE_HOST','host.docker.internal') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}" 
      user: "{{ env_var('CLICKHOUSE_USER','dbt_user') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD','dbt_password') }}"
      secure: false
      verify: false