services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    env_file:
      - .env
    ports:
      - "${CLICKHOUSE_PORT:-8123}:8123"
      - "9000:9000"
    volumes:
      - ./ch_data:/var/lib/clickhouse
      - ./ch_logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=${CLICKHOUSE_DATABASE:-default}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-dbt_user}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-dbt_password}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q 'Ok'"]
      interval: 5s
      timeout: 3s
      retries: 30
